#!/bin/sh

ppp_hook() {
	
	logger -t ip-utils "ppp_hook called:$@" 

	UPDOWN=$1
	TAG="ip-$UPDOWN-script"
	INTERFACE=$2

	logger -t $TAG "$0 called with params: $@"
	logger -t $TAG "interface '$INTERFACE' is $UPDOWN"

	if [ -n "$INTERFACE" ]
	then
		SCRIPT="/etc/ppp/ip-$UPDOWN.d/$INTERFACE"
		if [ -x "$SCRIPT" ]
		then
			logger -t $TAG "start script:$SCRIPT for interface:$INTERFACE"
			source $SCRIPT $@ 
		else
			logger -t $TAG "no $UPDOWN-script or script is not runnable:'$SCRIPT'"
		fi
	else
		logger -t $TAG -p user.warn "interface is null"	
	fi
}

logger -t ip-utils "ip-utils included."
