#!/bin/sh
# Copyright (C) 2014 marstone.net

VPNDEV="pptp-blockcn"
CNDEV="pppoe-wan"
LOCK="/tmp/pptp-blockcn.lock"
PID=$$

lock() {
	logger "try to get lock:$LOCK"
    for i in 1 2 3 4 5 6
	do
		if [ -f $LOCK ]; then
			logger "got $LOCK , sleep 10 secs. #$i/6"
			sleep 10
		else
			break
		fi
	done

    if [ -f $LOCK ]; then
		logger "still got $LOCK , I'm aborted. fix me."
		$ERROR='no lock'
		exit 0
	fi
	
	# create the lock
	logger "lock got." >> $LOCK
}

unlock(){
    # release the lock
    rm -f $LOCK
}


start() {
	lock

	iptables -D POSTROUTING -t nat -o pptp-blockcn -j MASQUERADE

	logger "adjust default route to $CNDEV"
	ip route del default
	ip route add default dev $CNDEV

	logger "restarting dnsmasq..."
	/etc/init.d/dnsmasq restart
	unlock
}

start &
