#!/bin/sh
# Copyright (C) 2014 marstone.net

VPNDEV="xl2tpd-client"
CNDEV="wlan1"
LOCK="/tmp/$VPNDEV.lock"
PID=$$

IFACE=$6
if [ -x $IFACE ] || [ ! $FACE = $VPNDEV ]; then
        logger "not $VPNDEV. actual: $IFACE. exit."
        exit
fi

lock() {
	logger "try to get lock:$LOCK"
    for i in 1 2 3 4 5 6
	do
		if [ -f $LOCK ]; then
			logger "got $LOCK , sleep 10 secs. #$i/6"
			sleep 10
		else
			break
		fi
	done

    if [ -f $LOCK ]; then
		logger "still got $LOCK , I'm aborted. fix me."
		$ERROR='no lock'
		exit 0
	fi
	
	# create the lock
	logger "lock got." >> $LOCK
}

unlock(){
    # release the lock
    rm -f $LOCK
}


start() {
	lock

	iptables -D POSTROUTING -t nat -o $VPNDEV -j MASQUERADE

	logger "adjust default route to $CNDEV"
	ip route del default
	ip route add default via 192.168.200.1 dev $CNDEV

	logger "not restarting dnsmasq..."
	# /etc/init.d/dnsmasq restart
	unlock
}

start &
