#!/bin/sh
# Copyright (C) 2014 marstone.net

VPNDEV="pptp-blockcn"
CNDEV="wlan1"
LOCK="/tmp/$VPNDEV.lock"
PID=$$

IFACE=$6
if [ -x $IFACE ] || [ ! $FACE = $VPNDEV ]; then
	logger "not $VPNDEV. actual: $IFACE. exit."
	exit
fi

lock() {
	logger "try to get lock:$LOCK"
    for i in 1 2 3 4 5 6
	do
		if [ -f $LOCK ]; then
			logger "got $LOCK , sleep 10 secs. #$i/6"
			sleep 10
		else
			break
		fi
	done

    if [ -f $LOCK ]; then
		logger "still got $LOCK , I'm aborted. fix me."
		$ERROR='no lock'
		exit 0
	fi
	
	# create the lock
	logger "lock got." >> $LOCK
}

unlock(){
    # release the lock
    rm -f $LOCK
}


start() {
	lock
	COUNT=0
    while [ $COUNT -eq 0 ]
    do
		logger "waiting for '$CNDEV' connection..."
		sleep 2
		COUNT=$(route -n | grep $CNDEV | wc -l)
    done
    
	logger "internet connected. route count=$COUNT"

    if [ $COUNT -lt 100 ]; then
        # CNGW=$(uci get network.wan.gateway)
        # if [ $COUNT2 -gt 0 ]; then
        #    CNGW=$(ifconfig | grep pppoe-wan -A1 | grep -Eo "P-t-P:([0-9.]+)" | cut -d: -f2)
        # fi
	CNGW="192.168.200.1"
        /etc/ppp/ip-route add /etc/ppp/ipwhite "via $CNGW"
        /etc/ppp/ip-route add /etc/ppp/ipcn "via $CNGW"
    fi


#	iptables -A POSTROUTING -t nat -o $VPNDEV -j MASQUERADE

#        iptables -A INPUT -i $VPNDEV -j zone_vpn_input
#        iptables -A FORWARD -i $VPNDEV -j zone_vpn_forward
#        iptables -A OUTPUT -o $VPNDEV -j zone_vpn_output
#        iptables -A zone_vpn_dest_ACCEPT -o $VPNDEV -m conntrack --ctstate INVALID -j DROP
#        iptables -A zone_vpn_dest_ACCEPT -o $VPNDEV -j ACCEPT
#        iptables -A zone_vpn_dest_REJECT -o $VPNDEV -j reject
#        iptables -A zone_vpn_src_REJECT -i $VPNDEV -j reject

	VPNGW=$(ifconfig | grep $VPNDEV -A1 | grep -Eo "P-t-P:([0-9.]+)" | cut -d: -f2)
	logger "adjust default route to $VPNDEV via $VPNGW"
	ip route del default
	ip route add default via $VPNGW dev $VPNDEV

	logger "restarting dnsmasq..."
	/etc/init.d/dnsmasq restart
	unlock
}

start &
