#!/bin/sh
# Copyright (C) 2020 marstone.net
# 0:/etc/ppp/ip-up.d/route-cn 1:l2tp-flowvpn 2: 3:0 4:10.10.10.2 5:10.10.10.1 6:flowvpn
# logger "0:$0 1:$1 2:$2 3:$3 4:$4 5:$5 6:$6"

APP="[Route-CN]"
FLOWVPN="l2tp-flowvpn"
CNGW="192.168.200.1"

if [ -x $1 ] || [ ! $1 = $FLOWVPN ]; then
        logger "$APP not $FLOWVPN. actual: $IFACE. exit."
        exit
fi

COUNT=$(route -n | grep $CNGW | wc -l)
if [ $COUNT -lt 100 ]; then
	logger "$APP start to route CN ip via $CNGW..."
	/etc/ppp/ip-route add /etc/ppp/ipwhite "via $CNGW"
        /etc/ppp/ip-route add /etc/ppp/ipcn "via $CNGW"
else
	logger "$APP already routed. CN routes:$COUNT"
fi

logger "$APP done. CN routes:$COUNT" 
